version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels: ["dependencies","github-actions"]
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:10"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels: ["dependencies","python"]
    groups:
      python:
        patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:20"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels: ["dependencies","docker"]
