version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "cron"
      cronjob: "0 4 * * *"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 100
    rebase-strategy: "auto"
    labels: ["dependencies","github-actions"]
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "cron"
      cronjob: "10 4 * * *"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 100
    rebase-strategy: "auto"
    labels: ["dependencies","python"]
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "cron"
      cronjob: "20 4 * * *"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 100
    rebase-strategy: "auto"
    labels: ["dependencies","docker"]
  - package-ecosystem: "docker-compose"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "cron"
      cronjob: "30 4 * * *"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 100
    rebase-strategy: "auto"
    labels: ["dependencies","docker-compose"]
